apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tailscale.fullname" . }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    # resourceNames: [{{ printf "%s-state" (include "tailscale.fullname" .) | quote }}]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch"]
{{- if .Values.podTopology.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tailscale.fullname" . }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
{{- end }}
