{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "link-common.fullname" . }}
  labels:
    {{- include "link-common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "link-common.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.wireguard.enabled }}
    - ports:
        - port: 51820
          protocol: UDP
    {{- end }}
    {{- if .Values.service.ports }}
    - ports:
        {{- range $key, $value := .Values.service.ports }}
        - port: {{ .port }}
        {{- end }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        {{- if or .Values.networkPolicy.ingressNSMatchLabels .Values.networkPolicy.ingressNSPodMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- if .Values.networkPolicy.ingressNSMatchLabels }}
              {{- .Values.networkPolicy.ingressNSMatchLabels | nindent 16 }}
              {{ else }}
                {}
              {{- end }}
          {{- with .Values.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- toYaml . | nindent 16 }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.wireguard.metrics.enabled }}
    # Allow scrapes for metrics
    - ports:
        - port: 9586
          protocol: TCP
      {{- if or .Values.networkPolicy.metrics.ingressNSMatchLabels .Values.networkPolicy.metrics.ingressNSPodMatchLabels }}
      from:
        - namespaceSelector:
            matchLabels:
              {{- if .Values.networkPolicy.metrics.ingressNSMatchLabels }}
              {{- .Values.networkPolicy.metrics.ingressNSMatchLabels | nindent 16 }}
              {{ else }}
                {}
              {{- end }}
          {{- with .Values.networkPolicy.metrics.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- toYaml . | nindent 16 }}
          {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
